### ISSUE TITLE
Different types of display in DrawingControl buttons?

### ISSUE THREAD

**Issue by GustavoCunhaLacerda** [amcharts/amcharts5#1133]
Is there any way to put another type of display in DrawingControl buttons?
I want put this controls in flex but i looked the source code and the "block" option is hard coded.

![image](https://github.com/amcharts/amcharts5/assets/48692606/28284018-6139-4505-983e-8756a85cb8c2)

```ts
// @amcharts/amcharts5/.internal/charts/stock/toolbar/DrawingControl.js
// Line 425
this.getPrivate("toolsContainer").style.display = "block";
```

**Comment by martynasma** [comment]
There's no way to do that via code.

However, you could probably still override it using CSS `!important` modifier.

**Comment by GustavoCunhaLacerda** [comment]
Ok, i solved the problem  with:

```ts
drawingControl.events.on("click", () => {
      self.$data.isDrawActive = Boolean(drawingControl.get("active"));
});
```
This code in the control div class:

```ts
!isDrawActive ? 'hide-draw-controls' : 'show-draw-controls'
```

And finally css:

```css
.hide-draw-controls .am5stock-control-drawing-tools {
  display: none !important;
}

.show-draw-controls .am5stock-control-drawing-tools {
  display: flex !important;
}
```

Looks like a trick and not the final solution. But if there is no other way this will be the final solution.

Have a chance to add a property to change the style of those intern divs in a future update? Can i open a PR if necessary?
